DROP DATABASE IF EXISTS mvc;
DROP USER IF EXISTS `mvc_admin`@`%`;
CREATE DATABASE IF NOT EXISTS mvc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `mvc_admin`@`%` IDENTIFIED WITH mysql_native_password BY 'mvc_admin_pass';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `mvc`.* TO `mvc_admin`@`%`;